export const APP_PROP_APP_TYPE = 'washMall'
export const APP_PROP_CLIENT = 'wx'
export const APP_PROP_CUID = '123'
export const APP_PROP_VERSION = '1.0.0'
export const APP_PROP_FORMAT = 'json'
export const APP_PROP_SECRET = 'Er78s1hcT4Tyoaj2'